### ISSUE TITLE
Adapt CSP for fonts and images

### ISSUE THREAD

**Issue by carlobeltrame** [juliushaertl/theming_customcss#17]
Hi! Great app you have here.
I have run into a problem, maybe you have an idea how to solve this:
I use Custom CSS to change the font that is used in the Nextcloud web interface. This works by defining the `@font-face`s and then using the following CSS:
```css
@font-face {
  font-family: 'my-desired-custom-font';
  font-style: italic;
  font-weight: 400;
  src: url(/fonts/my-desired-custom-font.woff2) format('woff2');
}

:root {
  --font-face: 'my-desired-custom-font', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen-Sans, Cantarell, Ubuntu, 'Helvetica Neue', Arial, 'Noto Color Emoji', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'
}

body {
  font-family: var(--font-face);
}

input, textarea, select, button, div[contenteditable="true"] {
  font-family: inherit;
}

input, textarea, select, button, div[contenteditable="true"] {
  font-family: inherit;
}
```

Now the problem is the source of the font files. I could host them directly on the nextcloud server, but the integrity check doesn't like **any** additional files anywhere except in the data directory, and I cannot serve the files directly from the data directory (.woff2 files are served directly from anywhere in the application directory, except for the data directory).

I could add them to the nextcloud admin's files and create publicly shareable links, but that would not be as performant as I would like my fonts to be I think (I'd like to keep the font swapping blinking as short as possible).

Next I tried to host the font files externally, but then the CSP of nextcloud blocks them, since it only allows `font-src: 'self' data:`.

So this means I could add the font files as `data:` urls inline in the CSS as well, but ideally I'd like to avoid that since the files are 132KB, and you apply cache busting for the custom CSS as far as I can tell.

How would you solve this problem? I could write a PR for this app to add more fields below the custom CSS input that allow admins to add font-src and img-src (for e.g. background images used in the custom CSS) to the content security policy. Is that also the solution you would choose? Would you accept a PR for this?

The only other solution I see is for me to create a dedicated app for our branding, and stop using your custom CSS app, which sounds like overkill to me.
